### ISSUE TITLE
Crash with POD-Bot MM

### ISSUE THREAD

**Issue by classc7601** [FWGS/xash3d-fwgs#699]
OS: Windows 7 64-Bit Edition
Game: Counter-Strike Beta 6.5
Client: FWGS 0.20
Metamod: P-37
Metamod Addons:
PODBot-MM R2b46d
AMX Mod 2010.1
Error: Game crashes with the error "assert failed at D:\a\xash3d-fwgs\xash3d-fwgs\engine\server\sv_game.c:4153" after the bots starting to join

**Comment by classc7601** [comment]
I must say it also happens with ANY version of Counter-Strike with ANY bots.

**Comment by Vladislav4KZ** [comment]
I wrote about this earlier...
https://github.com/FWGS/xash3d-fwgs/issues/399

**Comment by classc7601** [comment]
I don't know Russian, thanks for adding it here. So if there are more people with this error, I hope the developers will take care of it.

**Comment by a1batross** [comment]
Must be fixed in ca3544d5.

**Comment by unattendedplayer** [comment]
It is not fixed. I tried it with the same bots, CS 1.6 and it's giving out the error
![resim](https://user-images.githubusercontent.com/118223558/201770558-03ce761d-6e8a-4af8-a3d3-b218a449cdfd.png)
"assert failed at D:\a\xash3d-fwgs\xash3d-fwgs\engine\server\sv_game.c:4205".
Interestingly it works in **0.19.x**?
But **I have to** use this version so I can use **vgui2-support** version.
_I lost my account, so I had to create another._

**Comment by Vladislav4KZ** [comment]
Yeah, there is still a unclosed issue with it https://github.com/FWGS/xash3d-fwgs/issues/834
